name: article-illustrator
display_name: "Scrapbook-Style Illustration Inserter"
version: 1.3.0
description: >
  Insert scrapbook-style illustrations into articles using GLM-Image or OpenRouter.
  Analyzes article sections, generates hand-crafted scrapbook image prompts, creates images,
  and returns the full article with images embedded. Supports GLM and OpenRouter providers
  with auto-detection, margin guard for edge clipping prevention, and per-image cost display.
attribution:
  source: https://github.com/ViffyGwaanl/glm-image
  author: ViffyGwaanl
  license: MIT
permissions:
  - exec
  - read
triggers:
  - illustrate this article
  - add images to this article
  - generate pictures for this post
  - illustrate my post
  - add illustrations
  - illustrate in english
  - illustrate in chinese
